# docker-compose.yml

version: "3.7"
name: MyBlog

services:
  flask_app: # 서비스 이름
    build:
      context: ./flask_app # 도커 이미지 빌드 경로
      dockerfile: Dockerfile # 도커 파일 이름 지정
    container_name: flask_app # 컨테이너 이름
    restart: always
    command: gunicorn -b 0.0.0.0:8888 app:app
    # ports:
    #   - "8888:8888" # 호스트 포트 -> 컨테이너 포트

  nginx_server: # 서비스 이름
    build: 
      context: ./nginx # 도커 이미지 빌드 경로
      dockerfile: Dockerfile # 도커 파일 이름 지정
    container_name: nginx_server # 컨테이너 이름
    restart: always
    ports:
      - "0.0.0.0:18080:18080" # 호스트 포트 -> 컨테이너 포트
    depends_on:
      - flask_app