name: Deploy to EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# ------------------------- 환경 변수 설정 -------------------------
env:
  PROJECT_NAME: MyBlog
  BUCKET_NAME: myblog-wooyoung-bucket
  CODE_DEPLOY_APP_NAME: MyBlog_CodeDeploy
  DEPLOYMENT_GROUP_NAME: MyBlog_CodeDeploy_Group
  
# ------------------------- 작업 설정 -------------------------
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            cd MyBlog_project
            git pull origin main
            chmod +x run_docker.sh
            ./run_docker.sh
